export { default as CalenderImg } from '../assets/campaigns/group/calendar.png'
export { default as FileImg } from '../assets/campaigns/group/file.png'
export { default as PriceImg } from '../assets/campaigns/group/Price.png'
export { default as ReportImg } from '../assets/campaigns/group/statistics-report.png'

export { default as G1 } from '../assets/campaigns/thumbs/t1/Bitmap.png'
export { default as G2 } from '../assets/campaigns/thumbs/t2/Bitmap.png'
export { default as G3 } from '../assets/campaigns/thumbs/t3/Bitmap.png'
export { default as G4 } from '../assets/campaigns/thumbs/t4/Bitmap.png'
export { default as G5 } from '../assets/campaigns/thumbs/t5/Bitmap.png'
export { default as G6 } from '../assets/campaigns/thumbs/t6/Bitmap.png'
export { default as G7 } from '../assets/campaigns/thumbs/t7/Bitmap.png'
export { default as G8 } from '../assets/campaigns/thumbs/t8/Bitmap.png'
